name: lint
on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - run: yarn install
      - run: yarn run lint
